apiVersion: apps/v1
kind: Deployment
metadata:
  name: cybertask-frontend
  namespace: cybertask-staging
  labels:
    app: cybertask-frontend
    environment: staging
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  selector:
    matchLabels:
      app: cybertask-frontend
  template:
    metadata:
      labels:
        app: cybertask-frontend
        environment: staging
    spec:
      containers:
      - name: frontend
        image: ghcr.io/jmanhype/cybertask-frontend:IMAGE_TAG
        ports:
        - containerPort: 8080
        env:
        - name: NODE_ENV
          value: "staging"
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "250m"
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 3
        securityContext:
          allowPrivilegeEscalation: false
          runAsNonRoot: true
          runAsUser: 1001
          capabilities:
            drop:
            - ALL
---
apiVersion: v1
kind: Service
metadata:
  name: cybertask-frontend-service
  namespace: cybertask-staging
  labels:
    app: cybertask-frontend
    environment: staging
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
  selector:
    app: cybertask-frontend