services:
  - type: web
    name: cybertask-backend
    env: node
    repo: https://github.com/jmanhype/cybertask.git
    buildCommand: cd backend && npm install && npm run build
    startCommand: cd backend && npm start
    plan: free
    region: oregon
    branch: main
    rootDir: backend
    healthCheckPath: /api/health
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: DATABASE_URL
        fromDatabase:
          name: cybertask-postgres
          property: connectionString
      - key: JWT_SECRET
        generateValue: true
      - key: CORS_ORIGIN
        value: https://cybertask.onrender.com
      - key: RATE_LIMIT_WINDOW_MS
        value: 900000
      - key: RATE_LIMIT_MAX_REQUESTS
        value: 100

  - type: web
    name: cybertask-frontend
    env: static
    repo: https://github.com/jmanhype/cybertask.git
    buildCommand: cd frontend && npm install && npm run build
    staticPublishPath: frontend/dist
    plan: free
    region: oregon
    branch: main
    rootDir: frontend
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    envVars:
      - key: VITE_API_URL
        value: https://cybertask-backend.onrender.com/api
      - key: VITE_WS_URL
        value: wss://cybertask-backend.onrender.com
      - key: VITE_APP_NAME
        value: CyberTask
      - key: VITE_APP_VERSION
        value: 1.0.0

databases:
  - name: cybertask-postgres
    plan: free
    region: oregon
    postgresMajorVersion: 15